### ISSUE TITLE
Small Business and subsidiaries

### ISSUE THREAD

**Issue by bradrydzewski** [polyformproject/polyform-licenses#13]
This is awesome stuff.  I just wanted to mention that my small business waiver includes text that states `counting all subsidiaries and affiliated entities as one`. I have had customers reference this text explicitly in conversations, which leads me to believe it may be a useful clarification.

**Comment by kemitchell** [comment]
The looseness of "affiliated" is why legal forms tend to define "affiliate", and then define "control" to do so.

**Comment by bradrydzewski** [comment]
I missed the section that defines __Your Company__ and __Control__. Sorry for the false positive.
