### ISSUE TITLE
Looking good

### ISSUE THREAD

**Issue by groovyd** [polyformproject/polyform-licenses#16]
We are very interested in a license model specifically for the purpose of open-sourcing the Kaneva gaming engine to be free for personal and non-commercial (platform cooperative) use and that commercial interests must negotiate their license terms directly with the original owner of the engine source code.  A few of the old developers for Kaneva are planning to fork this to release a derivative game platform that will be organized as a platform cooperative and purely not for profit (ie. users are members and each have a vote on game features and their membership fees go to only paying the running costs of the servers).

Will be very interested in hearing more about the feasibility of using some form of this license to open-source the engine as soon as possible.

**Comment by kemitchell** [comment]
Good to hear from you, @groovyd.
