### ISSUE TITLE
permitted purpose for open source software

### ISSUE THREAD

**Issue by bradrydzewski** [polyformproject/polyform-licenses#23]
Would you consider a permitted purpose for open source software (lowercase)? I am thinking about developers tools as the use case. Initially I was thinking the non-commercial clause could work, however, this may be too broad for companies that sell to governments.

**Comment by kemitchell** [comment]
@bradrydzewski do you mean, effectively, a copyleft license? I don't expect Polyform will do a copyleft license.

**Comment by bradrydzewski** [comment]
I guess it does feel more like a Copyleft license with a Small Business waiver. Ignore me :)
