### ISSUE TITLE
Code names for license variations?

### ISSUE THREAD

**Issue by kemitchell** [polyformproject/polyform-licenses#34]
To date, we've mostly spoken about publishing variant licenses Creative Commons style. `Polyform-SB`, `Polyform-NX-IB`, and so on.

But it's occurred to @heathermeeker and I that the "baseline" noncommercial license will probably have the changes and distribution add-ons in it. `Polyform-CL-DL` doesn't exactly say "base license" to everyone else, and needlessly exposes implementation details.

I would prefer to come up with distinctive names, descriptive or complete fanciful, for each of the variants. In fact, I might _prefer_ fanciful names. Perhaps the names of well known polyforms, well known polyform base polygons, or famous mathematicians?

**Comment by nothingismagick** [comment]
This is fun. I'll give it some thought over the weekend.

**Comment by kemitchell** [comment]
@nothingismagick any thoughts here? We're pushing toward a 1.0.0 pretty soon!

**Comment by nothingismagick** [comment]
# fanciful
 
Changes License - Chameleon
Distribution License - Dandelion
Free Trial - Baker’s Dozen
Small Business - Anthill
Internal Business - Beehive
Noncompete - Mongoose

**Comment by nothingismagick** [comment]
Maybe chemical elements could work too...

But what is the final list of licenses?

**Comment by heathermeeker** [comment]
I love those suggestions (particularly beehive), but I'm leaning away from this approach because I think it will be too confusing for the uninitiated. We might dispense with the two-letter codes, though, except in SPDX.  Thus "Non-Commercial" with an identifier of Polyform-NC. I'd love to do some sub-branding for each version.  For example Internal (beehive) could use a hexagon, small business a triangle, etc.

**Comment by kemitchell** [comment]
I'd be alright with descriptive names, rather than jumbles of two-letter codes.

**Comment by kemitchell** [comment]
Sketching:

`Polyform-Noncommercial` = Base + CL + DL

`Polyform-Strict` = Base only

`Polyform-Small` = Base + CL + DL + SB

`Polyform-Trial` = Base + CL + DL + FT

`Polyform-Internal` = Base + CL + DL + IB

`Polyform-Noncompete` = Base + CL + DL + NX

**Comment by heathermeeker** [comment]
I like this.

**Comment by kemitchell** [comment]
@heathermeeker I keep going back and forth about the Changes and New Work License. I think we need at least one variant without that permission. And I could hypothesize use cases for other variants, like Internal Use without Changes. But on the other hand, we've always spoken about these forms as source-available licenses, and giving people source seems to invite changes, whether your terms do or not.

**Comment by heathermeeker** [comment]
I think it should be an option.  I get far fewer inquiries about a no-changes license than the others.  Also I think we want to avoid the whole linking-additions-is-a-derivative-work question, so I think of it in terms of changes.

**Comment by kemitchell** [comment]
Closing this one. We can take up names for additional variants on a one-off basis going forward.
