### ISSUE TITLE
Agreement and Licenses

### ISSUE THREAD

**Issue by kemitchell** [polyformproject/polyform-licenses#49]
Responding here to a few points @heathermeeker brought up in review drafts ahead of 1.0.0.

Following in the steps of [Blue Oak Council's model permissive license](https://blueoakcouncil.org/license/1.0.0), Polyform licenses avoid the "contract or license?" morass by answering "both". Polyform licenses don't grant licenses _unless_ the would-be licensee agrees to their terms.

From the would-be user's point of view:

User &rarr; Contract &rarr; Licenses

 [Acceptance](https://github.com/polyformproject/polyform-licenses/blob/4247eb08bcb6ee8dcada3305fa532ce1807707a8/polyform.md#acceptance) spells this out, as does the definition of "your licenses":

> **Your licenses** are all the licenses granted to you for the software under these terms.

Licenses very much plural. Even under `Polyform-Strict`, there are two: [Copyright License](https://github.com/polyformproject/polyform-licenses/blob/4247eb08bcb6ee8dcada3305fa532ce1807707a8/polyform.md#copyright-license) and [Patent License](https://github.com/polyformproject/polyform-licenses/blob/4247eb08bcb6ee8dcada3305fa532ce1807707a8/polyform.md#patent-license). Under other variants, like `Polyform-Noncommercial`, there are more: [Distribution License](https://github.com/polyformproject/polyform-licenses/blob/4247eb08bcb6ee8dcada3305fa532ce1807707a8/polyform.md#dl-distribution-license) and [Changes and New Works License](https://github.com/polyformproject/polyform-licenses/blob/4247eb08bcb6ee8dcada3305fa532ce1807707a8/polyform.md#cl-changes-and-new-works-license).

The licenses granted are also meaningfully _independent_. [Patent Defense](https://github.com/polyformproject/polyform-licenses/blob/4247eb08bcb6ee8dcada3305fa532ce1807707a8/polyform.md#patent-defense) terminates only the patent license. When that happens due to a claim by a company, rather than an individual, the patent license terminates only for work on behalf of that company.

Licensing through contract is so common _outside_ of open source that folks use "license", "contract", and "agreement" interchangeably.  The better forms for deals of the kind say explicitly that licenses granted terminate when the agreement terminates, either in the license grants ("for the term of this agreement") or in the sections covering termination and survival ("coterminous" &c.).

We currently do this in [Violations](https://github.com/polyformproject/polyform-licenses/blob/4247eb08bcb6ee8dcada3305fa532ce1807707a8/polyform.md#violations):

> Otherwise[, if you don't respond to notice by coming into compliance], your agreement and your licenses end immediately.

The trouble, as I see it, is that while we want to be clear about contract-and-licenses, that's fundamentally a wonkish legal thing. It's hard to write both.

The current "solution", which we landed on by accretion rather than any conscious design, is to write both "agreement" and "licenses" everywhere both matter:

> These terms are both obligations under your agreement and conditions to all your licenses.

> The licensor may not end your agreement, or revoke any of your licenses, except per Violations and Patent.

> If you are notified ... your agreement under these terms can nonetheless continue if you ....  Otherwise, your agreement and your licenses end immediately.

> **You** refers to the individual or entity agreeing to and receiving licenses under these terms.

I'll create a PR referencing this issue shortly, to try and address the issues holistically.

**Comment by heathermeeker** [comment]
Wouldn't it be "this agreement" instead of "your agreement"?

>>The licensor may not end your agreement, or revoke any of your licenses, except per Violations and Patent.
A licensee cares about rights, not an agreement.  The agreement is about the licensee's covenants, not the licensor's.

>>If you are notified ... your agreement under these terms can nonetheless continue if you .... Otherwise, your agreement and your licenses end immediately.

I think "your agreement" is awkward and it should be, if necessary, "this agreement"
