### ISSUE TITLE
Clarify that any rule breach is material?

### ISSUE THREAD

**Issue by kemitchell** [polyformproject/polyform-licenses#5]
We presume that nearly any failure to satisfy a license condition creates risk of infringement claims.  But contract law has a whole case law of breach materiality.  It isn't clear from the current text that _any_ breach of _any_ rule triggers Excuse.

Should Excuse state explicitly that any rule-breaking is material rule-breaking, and the deal (with its licenses) is off?

**Comment by heathermeeker** [comment]
Yes I think that is a good idea.

**Comment by kemitchell** [comment]
@heathermeeker this should affect Blue Oak's model and my API Copyleft License, as well.
