### ISSUE TITLE
Unclear Permitted Purposes in Small Business

### ISSUE THREAD

**Issue by turbo** [polyformproject/polyform-licenses#58]
In the non-commercial license, the constraint sections "Noncommercial Purposes", "Personal Uses", and "Noncommercial Organizations" each explicitly mention "permitted purpose". 

The Small Business license contains the phrase "for any permitted purpose" in "Changes and New Works License", but then doesn't actually define those purpose expletively. It might be implied by prior paragraphs, but when reading SB and NC side-by-side one could almost get the impression that SB is *only* for business licensees and Personal Use is not a permitted purpose. I've gotten similar feedback from a few people who I showed the licenses to.

I guess the easiest way to clarify would be to include the "Personal Uses" in SB, too.

**Comment by kemitchell** [comment]
@turbo The titular section of the Small Business license begins:

> Use of the software for the benefit of your company is use for a permitted purpose if ...

No other section of that license adds any other permitted purpose.  So there is just one: benefiting "your company", if "your company" comes under the personnel and revenue limits.

Note that "your company" is also a defined term. It includes sole proprietors:

> **Your company** is any legal entity, sole proprietorship, or other kind of organization that you work for...

Some licensors may choose to make their work available under both Polyform Noncompete and Polyform Small Business.

**Comment by turbo** [comment]
Thanks, but that didn't actually answer my question. "Sole proprietor" is defined as

> a person who is the exclusive owner of a business, entitled to keep all profits after tax has been paid but liable for all losses; a sole trader.

Which seems to imply to me that SB is *exclusively* for commercial purposes, which is not what I expected. I'm familiar with other licenses which restrict by business size but are not commercial-only. If that's not what it means, then I'm confused as to why the NC license *does* include personal use explicitly. I guess it would be nice to have a "Personal Use" feature column in the overview and especially on the website in any case.

> under both Polyform Noncompete and Polyform Small Business

What Noncompete license? Now I'm really confused.

**Comment by turbo** [comment]
N.b.: The licenses I was hoping to find are these:

Generic non-commercial. 

I don't think the P-NC is a good fit. It includes "government institution"s, regardless of the origin of funding, which I don't agree with. It's also a really broad term, complicated by some constructs and semi-recent court cases in Germany. I'd have preferred an exclusion based on intent, specifically the intent to commercially offer (in any form) the licensed project as the sole or major part of a product or service by the licensee.

Generic small-business.

MIT-like rights, LL, patent grant, for any purpose (including non-commercial). Commercial purposes limited to licensees which fulfill a given definition of small business. I don't think P-SB fits this, but I could be wrong.

**Comment by kemitchell** [comment]
@turbo I fat-fingered above.  Licensors can choose to offer code under both Polyform-Noncommercial and Polyform-Small-Business if they so choose. That has the effect of adding small business permission on top of noncommercial permission.

**Comment by kemitchell** [comment]
@turbo, if you essentially want CC-NC for software, have a look at [Prosperity](https://licensezero.com/licenses/prosperity), a license I wrote for a different project. Both individuals and companies have used it successfully.

Prosperity essentially transplants CC-NC's intent-based rule into a permissive software license. It therefore inherits all of the problems we know of CC-NC, which I think would afflict your proposal, as well.

As a practical matter, many overwhelmingly noncommercial organizations refuse to whitelist CC-NC by policy, because they can't effectively monitor occasional arguably commercial uses. That induces widespread false negatives: many individuals within those organizations can't practically use CC-NC works, even though they qualify under the license terms.

There is no "correct", faultless definition of noncommercial, in software or anywhere. Only trade-offs. CC-NC/Prosperity and Polyform make different choices.

If you could link to the German cases on "government institutions", we'd be grateful!  We'd be especially grateful for an introduction to English-writing German counsel that we could welcome to the project. Broader non-US vetting is definitely on our roadmap for future versions.

**Comment by turbo** [comment]
Thank you for your detailed answers. It seems like NC+SB might be the best options for me. After reading Creative Common's essay on their NC license and the problems and unintended effects it causes, an intent-based approach seems indeed inferior when looking at adoption. A struggle I've seen first-hand in my current position.

---

What follows are some tips to get your hands on German counsel relevant to this project:

For Germany, Beck has one of the best-vetted lists of legal folks for their informal Blog outlet. If you take a look at the current listing [here](https://community.beck.de/experten) and look for areas called IT-Recht (IT law), IT-Sicherheitsrecht (IT security law), Telekommunikationsrecht (a catch-all, very old term for most of telecommunication, which includes much of the internet) and Legal Tech (...) you'll find the people who you'd probably want to talk to. Take a look at their posts. I recommend using [DeepL](https://www.deepl.com/en/translator) for translating between English and German, as it's almost indistinguishable from a perfect translation, even for complicated subjects like legal prose. You need to create a login to view their profile. German professionals can be contacted via Xing, LinkedIn. Most of these people do of course speak English. Another person of interest would be Leonhard Dobusch, who teaches trans-national (copyright among other things) at the University of Innsbruck and is an author for the high-profile digital rights publication netzpolitik.org.

**Comment by kemitchell** [comment]
@turbo Thanks so much for that information!
