### ISSUE TITLE
add traditional commercial license

### ISSUE THREAD

**Issue by monadic** [polyformproject/polyform-licenses#59]
it would be useful to add a traditional unrestricted commercial license to this group, using the same laconic style

**Comment by kemitchell** [comment]
What do you mean by "traditional unrestricted"? Perhaps you could pick the closes one of the existing Polyform licenses, and sketch the differences?

**Comment by monadic** [comment]
Sorry, what I mean is a license more or less equivalent to a typical non-free closed source EULA from a software company.  

I understand Polyform (good name!) licenses are intended to craft a scope of FREE use, yes?  And the set of licenses form a suite, perhaps inspired by Creative Commons.  In CC, we can fall back to traditional copyright should none of the licenses suit our purpose.  In PF, a licensor could fall back to a non-free license.  Eg, you might say "free for SMBs under PF-SMB, otherwise paid under PF-EE".

**Comment by kemitchell** [comment]
Please don't apologize. Thanks for getting back to us.

I think nearly all the lawyers involved in Polyform are interested in doing more to standardized on the commercial side, too. But I don't think Polyform will publish a paid form in the foreseeable future.

There are several ways in which paid terms tend to differ from free terms. Unfortunately, each paid form often differs from other paid forms, too, in functionality as well as implementation. For example, paid terms tend to handle the method of payment, and the way payments are calculated. Flat fee? Subscription? Site license? Per-seat? Per-core? And so on.

For what it's worth, this repository includes [a license for the terms of the licenses themselves](https://github.com/polyformproject/polyform-licenses#license), so others can borrow and build on, so long as they respect the "Polyform" name and trademark.

**Comment by monadic** [comment]
I understand.  I think you could do it by factoring out the terms, see eg https://gitlab.com/gitlab-org/gitlab-ee/blob/master/LICENSE lines 8-9 for example.  

It would be genuinely useful to have a baseline, template EE license ;-)

**Comment by kemitchell** [comment]
There are many such forms and templates, but no standard. In part because there's so much variation.

**Comment by monadic** [comment]
Then there is no measurable downside to adding one more ;-)

**Comment by monadic** [comment]
Ps want to say thank you for making these licenses in this way (as a set, concise plain language, on GH).  Useful.

**Comment by kemitchell** [comment]
@monadic I am going to go ahead and close. I think the upshot here is essentially "out of scope".

That being said, I think you have the right people. Lots of lawyers who've contributed to Polyform are interested in paid-license standardization, too. But I don't think Polyform is the vehicle for that effort.
