### ISSUE TITLE
Relation of drafts in this repo to released versions?

### ISSUE THREAD

**Issue by mlinksva** [polyformproject/polyform-licenses#61]
Are the drafts in this repo intended to serve as working documents for `>1.0.0` versions where those [exist](https://polyformproject.org/licenses/)? In any case, it would be good to state what the intent is, and probably indicate the existence of released versions, in the README.

I'm doubtful `source text for [Polyform Project](https://polyformproject.org) licenses` is correct as the ones at the link are 1.0.0 rather than drafts. 😄

**Comment by kemitchell** [comment]
@mlinksva v1.0.0s are tagged in this repo, with GitHub releases. This is indeed the "working repo" for ongoing work on the terms.
