### ISSUE TITLE
Rename Polyform-Noncompete

### ISSUE THREAD

**Issue by kemitchell** [polyformproject/polyform-licenses#66]
A few folks have brought up potential confusion between Polyform-Noncommercial and Polyform-Noncompete at various times. I agree that they feel uncomfortably close and confusion-prone.

A few alternatives:

- Polyform-Competition
- Polyform-Competitive
- Polyform-Competitor
- Polyform-Nonrivalry
- Polyform-Protection

On first glance, I think I would prefer Polyform-Competition.

**Comment by mlinksva** [comment]
With the exception of Strict, the released Polyform licenses say what they allow. If Strict followed that I guess it would be something like Noncommercial Internal Unmodified Use?

Personally I'd live with the potential confusion: both noncommercial and noncompete are widely used terms and don't have fantastic...substitutes.

Noncompetitive Use might discourage confusion, is close to the expected term, even more clearly communicates what is allowed, and mirrors Internal Use.

However, of the alternatives you list I also prefer Competition.

**Comment by kemitchell** [comment]
@mlinksva, I immediately received private feedback against a rename, as well.

I agree that Polyform-Nonc* could trip some people up. But I think the obvious name for the license in Polyform-Noncompete. Both "noncommercial" and "noncompete" are established terms and concepts.
