### ISSUE TITLE
Rethinking Non-compete

### ISSUE THREAD

**Issue by heathermeeker** [polyformproject/polyform-licenses#68]
I have been very concerned about the direction of this clause, and so I am mulling over the idea of taking an approach like this:

"Compete" has its everyday meaning, informed by the considerations below.  "Product" includes any product or service. 

The following is irrelevant when interpreting the meaning of "compete":
-The form of either product (the licensor's product or your product), such as on-premises distribution, software-as-a-service, or a combination of them 
-The programming language in which the product is written
-Whether either product is provided free of charge
-Products the licensor may create or release after you receive the software under these terms
-Offering professional support for the software

The following is relevant when interpreting the meaning of "compete":
-whether you add significant additional value to the licensor's product, which would imply your product is not competing
-whether you charge separately for the licensor's product, which would imply your product is competing
-whether sales of your product result in cheaper or fewer sales of the licensor's product

The following, standing alone, is a sufficient condition that implies your product competes: you market your product as a substitute for the licensor's products

**Comment by kemitchell** [comment]
@heathermeeker would this appear within the broader framework of a prohibition on competing with the licensor, or competing with the licensed software?

**Comment by heathermeeker** [comment]
It is about the software, not the licensor.  This approach is intended to make people comfortable with that notion.  A prohibition on competing with an entity is a legal quagmire.  I have been doing M&A deals for 25 years, and it takes pages of text to deal with anti-competition provisions properly.  It raises antitrust issues and risks unenforceability.  It creates loopholes as entities change ownership or form.  This is a software license; the limitations should relate to the software. Anything beyond that is legally problematic, either because it creates loopholes or violates the law.

**Comment by kemitchell** [comment]
@heathermeeker as much conflict as there absolutely is about noncompete terms, I think that's what the people want---in licensing as in M&A. The more I've floated the product-based competition idea, the more I've realized that's fundamentally a new innovation as yet to be socialized and established, not a broad, preexisting demand we might standardize.

The principal issue is that many, many potential users of a competition-limiting license will release libraries, frameworks, tooling, or other partial inputs to the complete products and services they actually sell for money. The internal dialog is whether they can share those components publicly without simply empowering their competitors to save money or reach feature parity. So a 3D modeling company might release a solver library, but not if other database companies will just stick in their own competing modeling applications.

There are cases where companies actually consider releasing their main product or service. That's Mongo, for example. But a great many more consider releasing less than that. In the exceptional case where the software _is_ the main line of business, at least in theory, the distinction collapses. Competing with the software _is_ competing with the developer, and competing with the developer _is_ competing with their software.

Conversely, where the software _isn't_ the main line of business, licensors need licensor-based noncompetition to bring that main line within the scope of noncompetition. So from Confluent, in terms for add-ons to Kafka:

> For purposes of this Agreement, “Excluded Purpose” means making available any software-as-a-service, platform-as-a-service, infrastructure-as-a-service or other similar online service that competes with Confluent products or services that provide the Software.

A licensed-software-based noncompete in terms for add-on functionality would _not_ reach competition in provision of Kafka more generally.

**Comment by bradrydzewski** [comment]
@heathermeeker I was reading one of your previously suggested edits:

> It is not a permitted purpose for you to make available to other any offering that competes with the software.  To compete means that you market your offering as an economic substitute for the software, whether or not you provide it free of charge. 

I was wondering your thoughts on the following hypothetical that @mlinksva provided in a separate thread and how the non-compete would work with libraries?

> social networking startup develops library for querying graph databases, because they weren't satisfied with existing ones...they don't care what others do with this amazing new library, so long as other social networks can't use it

Could the non-complete include the software and any products or services that _use_ the software? Or any other thoughts on how to account for libraries?
