### ISSUE TITLE
Brainstorming Noncompete License Names

### ISSUE THREAD

**Issue by kemitchell** [polyformproject/polyform-licenses#74]
We're in the process of prepping two new Polyform licensees for publication. Both implement a kind of noncompete. One prohibits using the licensed project to compete with the project itself. The other prohibits using the licensed project to compete with the licensor, in addition to their project.

The word "noncompetition" or "noncompete" would describe either license. But of course we want names that are easy to tell apart, both from each other and from the Polyform licenses already released: Noncommercial, Strict, Internal, Small Business, Free Trial. Alas, we've already seen confusion of "noncompete" with "noncommercial". Understandably so.

If you have ideas about how to name the licenses, please do share them here. We're compiling a list, which we plan to share again with the group as a whole before deciding.

**Comment by kemitchell** [comment]
A few from my notepad, just to get us started:

- Polyform-Competitive
- Polyform-Protective
- Polyform-Singleton
- Polyform-Perimeter
- Polyform-Defensive
- Polyform-Collaborative

**Comment by kemitchell** [comment]
From others:
- Cooperation
- Symbiosis
- Fair Trade
- Enlightened Self Interest
- Golden Rule
- Invisible Hand
- Reciprocal Altruism
- Gift Economy

**Comment by heathermeeker** [comment]
From others:
Collaboration 
Joint Interest 
Shared Interest 
Co-Development 
Shared Development

**Comment by erlend-sh** [comment]
> Alas, we've already seen confusion of "noncompete" with "noncommercial".

The distinction between any of the polyform licenses was confusing to me until I actually read them all in full. That just seems unavoidable given the shared foundation of all the licenses. Noncompete and Noncommercial are both very important concepts that should be 

To me the best description remains “noncompete”, so I prefer the current names, though preferably in flipped order: Polyform-Noncompete-Project.

In the spirit of brainstorming I’ll add some to the pile:
Polyform-Pact
Polyform-Accord
Polyform-Covenant
Polyform-FairPlay ⭐️

**Comment by heathermeeker** [comment]
Thank you!

**Comment by heathermeeker** [comment]
From others:
No Competition
Different Market
Market Restricted
Different User
User Restricted

**Comment by heathermeeker** [comment]
Ecosystem

**Comment by heathermeeker** [comment]
From others:
collaboration license
cooperators license
collaborators license

**Comment by heathermeeker** [comment]
I like the symbiosis idea, and here is an interesting factoid:

There are five main symbiotic relationships: mutualism, commensalism, predation, parasitism, and competition

**Comment by kemitchell** [comment]
@heathermeeker it's a rich vein of analogy! But also different than the math/geometry one we've adopted for the project at large. We could end up with mixed-metaphor titles.

**Comment by bradrydzewski** [comment]
Another option could be `Polyform Noncompete` and `Polyform No Substitute`.  The former would prohibit competing with the licensor and the latter would prohibit competing with the product (i.e. prohibit providing a practical substitute).

**Comment by kemitchell** [comment]
@bradrydzewski using "Noncompete" for one and something else for the other came to my mind first, too.

@heathermeeker shared some concerns about "Noncompete" and "Noncommercial" getting confused. We've gone with longer identifiers, like `Polyform-Noncommercial`, instead of `Polyform-NC` and the like. But they're still very close.

One way to avoid that might be to prefix the titles differently, while using the same suffix:

- `Polyform-LicensorProtection`
- `Polyform-ProjectProtection`

**Comment by heathermeeker** [comment]
I would like to avoid anything that starts with "non"

**Comment by heathermeeker** [comment]
I have collected the above suggestions below with stars by the ones I like best.  Unless I hear otherwise, I will poll the larger group about the starred ones.  Let me know if you think I should include any others with the starred ones. I also think we should designate both licenses in process by the same name, and append Licensor or Software. 

Competitive 
Protective
Singleton
Perimeter*
Defensive
Collaborative*
Ecosystem*
Mutuality
Collaboration
Joint Interest
Shared Interest
Co-Development
Shared Development
collaboration
cooperators 
collaborators 
Symbiosis*
No Competition
Different Market
Market Segment*
Market Restricted
Different User
User Restricted
Pact*
Accord*
Covenant
FairPlay*
Cooperation*
Commensal*
Fair Trade
Enlightened Self Interest
Golden Rule
Invisible Hand
Reciprocal Altruism
Gift Economy

**Comment by kemitchell** [comment]
@heathermeeker should we identify which proposed name goes with which license, or present them in pairs?

**Comment by heathermeeker** [comment]
My idea was to pick one word, then append Licensor or Software to it. I don't think any of these obviously apply to one rather than the other, but I'm open to the idea if anyone thinks otherwise.

I will shortly send a poll to the groups.io list.
