### ISSUE TITLE
Reliability and rights to revoke

### ISSUE THREAD

**Issue by erlend-sh** [polyformproject/polyform-licenses#78]
Unlike Parity or Blue Oak, Polyform doesn’t have a Reliability clause (right lingo?).

Does a licensor have the right to revoke a Polyform license?

I.e. if I don’t like the way someone is using my Polyform-licensed tool, can I say “I revoke your license for this tool”?

**Comment by kemitchell** [comment]
The relevant language from Blue Oak:

> ## Reliability
> No contributor can revoke this license.

<https://blueoakcouncil.org/license/1.0.0#reliability>

**Comment by kemitchell** [comment]
@erlend-sh I cannot give free legal advice here. Please have a look at [notlegaladvice.law](https://notlegaladvice.law) for more on what that means, and why I say it.

In general, under US law, I do not think license grants under PolyForm terms could be readily revoked. It's potentially _arguable_, but I don't think any of the arguments are very strong. That might be clearer if we added in a section like Blue Oak's "Reliability" section, quoted earlier.

A couple inputs to that conclusion:

- Licenses can be revocable, but promises under contracts often aren't. PolyForm license go out of their way to present themselves as both. Have a look at the "Acceptance" sections, common to all the PolyForm licenses, which uses both contract-speak ("obligations") and license-speak ("conditions").

- Many old, common open source licenses, including MIT and BSD, say nothing about revocation. They don't say anything about being contracts, either. Most colleagues I know who do open licensing work still believe they're likely irrevocable in all or most cases.

- There have been occasional, conspiratorial claims that contributors to projects like the Linux kernel can revoke the licenses for their contributions. The legal analysis there often gets mixed up with the folk of kernel hackers, further confusing the issue. Suffice to say I'm not aware of anyone making good the threat to revoke the license for their kernel contributions for no reason, without also saying that someone violated the terms to begin with.

**Comment by kemitchell** [comment]
I'm going to close this one, since I think our original conversation resolved.

But relatedly, we are working ourselves up to do v2s of the PolyForm licenses. I've already included Blue Oak-style irrevocability language in working drafts.
