### ISSUE TITLE
What is "permitted purpose" in PolyForm-Free-Trial?

### ISSUE THREAD

**Issue by tamalsaha** [polyformproject/polyform-licenses#80]
I see not permitted purpose clause in `PolyForm-Free-Trial` license. Does that mean there is no permitted purpose? IANAL, so trying to make sure I understand it correctly.

**Comment by kemitchell** [comment]
@tamalsaha have a look at the "Free Trial" section of the license, or search for "permitted purpose" in the text.

**Comment by tamalsaha** [comment]
Thanks. I re-read it. I understand it now.
