### ISSUE TITLE
Can Shield be used for commercial purposes? 

### ISSUE THREAD

**Issue by jdrews** [polyformproject/polyform-licenses#85]
If the software is licensed with Polyform Shield, can it be used to build non-competing commercial applications? For instance, if the Polyform Shield licensed software is a web framework, could it be used to build a commercial website or commercial desktop application? 

Lastly, I think the [New Products](https://polyformproject.org/licenses/shield/1.0.0/#new-products) clause implies that the company owning the Polyform Licensed software decides to build a product that competes with my commercial product, I can no longer use any updated version of that software. Is this accurate? Seems like a heavy business risk if so.

**Comment by jdrews** [comment]
Context: I asked this question in a Polyform Shield licensed git repo here: https://github.com/micro/micro/discussions/1672

**Comment by kemitchell** [comment]
Here's the operative language:

> Any purpose is a permitted purpose, except for providing any product that competes with the software or any product the licensor or any of its affiliates provides using the software.

And on new products:

> If you are using the software to provide a product that does not compete, but the licensor or any of its affiliates brings your product into competition by providing a new version of the software or another product using the software, you may continue using versions of the software available under these terms beforehand to provide your competing product, but not any later versions.

**Comment by jdrews** [comment]
Thanks!
