### ISSUE TITLE
Regarding Noncommercial license variant: what is the scope of "government institution"?

### ISSUE THREAD

**Issue by erinmez** [polyformproject/polyform-licenses#86]
Hi there,

I'm intrigued by the noncommercial polyform license. I create software that IT departments in different government "agencies" use for their clerks. 

I was wondering, whether an IT department that sits somewhere in the Department of Defense/Transport etc. or an IT department in a municipality falls under the "Noncommercial Organizations" category in this license. I would like to treat those rather like commercial entities, meaning I would like to exclude those in this license.

I'm aware I can enrich the license myself (though it's not a polyform license anymore). Just was wondering whether they might be already excluded by definition.

Best,
Tanju

**Comment by kemitchell** [comment]
The relevant language, so we have it handy:

> Use by any charitable organization, educational institution, public research organization, public safety or health organization, environmental protection organization, or government institution is use for a permitted purpose regardless of the source of funding or obligations resulting from the funding.

There's not any hidden definition of "government institution" that I'm aware of, in the license or in law that may apply, at least here in the USA. Perhaps other countries _do_ have laws that try to clarify what that phrase means when used in private contracts. I'm not aware of any.

So we're left asking how a court would read the terms I quoted above.

I [can't stand professionally accountable to you for what I say in public GitHub issues](https://notlegaladvice.law). But if you're talking about IT departments that are part of government institutions, full of IT people who work for the government, I don't think I'd rely on PolyForm Noncommercial to exclude them from using for free.

There may also be situations where outside contractors get covered, such as when a government institution hires a commercial contractor to do government work that involves using the software. Those situations might go either way, if it went to court. We have seen a decision here in the USA where a commercial copy shop working for a university was covered by the Creative Commons NonCommercial license. But there have been some cases abroad, including one in Germany, where the court seemed to be stricter about noncommercial-type organizations using CC-NC material on behalf of noncommercial organizations.

**Comment by erinmez** [comment]
Hi @kemitchell , 

Thanks for your insight, much appreciated!

Best,
Tanju
