### ISSUE TITLE
Is Open Source Using Polyform Noncommercial License Violation of License If I Use It for Paid Consulting?

### ISSUE THREAD

**Issue by christian289** [polyformproject/polyform-licenses#89]
First of all, I'm not sure if I can post my question here.

I am curious about the content of the above question.

I work for a company and the company is developing an open source project.

I'm going to use this open source project to do paid consulting.

Of course, since it's open source, we'll make it available for other users to download, build, and run the source code.

Does this violate the PolyForm Noncommercial License 1.0.0 license?

**Comment by kemitchell** [comment]
If you need someone to stand professionally accountable for answering your legal question, please put it to the lawyers for your company.

For your notes and theirs, I'd point out that [PolyForm Noncommercial's terms](https://polyformproject.org/licenses/noncommercial/1.0.0/) only licenses for "permitted purposes", which are [defined to mean "noncommercial purposes"](https://polyformproject.org/licenses/noncommercial/1.0.0/#noncommercial-purposes). There are some special clarifications for [personal uses](https://polyformproject.org/licenses/noncommercial/1.0.0/#personal-uses) and [non-commercial organizations](https://polyformproject.org/licenses/noncommercial/1.0.0/#noncommercial-purposes).
