### ISSUE TITLE
Permit sharing of code between other licenssees?

### ISSUE THREAD

**Issue by inquisitiv3** [polyformproject/polyform-licenses#9]
Is it possible to in some way add an optional part to the `Distribution License` that the licensee is only allowed to distribute the software to other people or entities that hold the same permission?

I'm thinking of a future business model where I use the base license by default, but license the software with the DL, CL, and IB clauses for a fee. The optional addendum to the DL license would ensure for my customers that if I went out of business they still would be able to continue the development and share their work with other entities, e.g., security patches.

**Comment by kemitchell** [comment]
@inquisitiv3 there's nothing wrong with using a Polyform license as your public license, then offering exceptions or different terms for private sale. Once we get a public license in place for the text of the Polyform standards, you may very well be free to start from that language to write your private-license form.

However, I think using other Polyform public licenses as your private license terms is a type error. Selling a different public license is paid relicensing, not dual licensing / selling exceptions / [public-private licensing](https://indieopensource.com/public-private/indies). Public license forms, as written, give permission to _everyone_, not one specific company or individual.
