### ISSUE TITLE
It would be cool if there were a badge

### ISSUE THREAD

**Issue by nichoth** [polyformproject/polyform-licenses#90]
You know, for the README file. I've been using a generic one from shields.io

<img width="160" alt="screenshot of badge" src="https://github.com/polyformproject/polyform-licenses/assets/5776508/b4ee5165-ec6f-4750-b803-e3e41ae37b1f">

**Comment by kemitchell** [comment]
There are license-specific pictographs on the license list page: https://polyformproject.org/licenses/

**Comment by nichoth** [comment]
easy to link badge with a small shield image

https://github.com/nichoth/badge
